name: NodeJS Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkoutev3 # checkout
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm-install
      - name: Run test
        run: npm-test